apiVersion: v1
kind: Service
metadata:
  name: rent-predictor-service
spec:
  type: LoadBalancer # Core: Automatically request external public IP addresses from GCP
  ports:
  - port: 80         # The port accessed by the user (standard HTTP port 80)
    targetPort: 8000 # Mapped to the FastAPI 8000 port inside the container
  selector:
    app: rent-predictor